@Service1_HostAddress = http://localhost:5001

GET {{Service1_HostAddress}}/
Accept: application/json

###

GET {{Service1_HostAddress}}/swagger/index.html
Accept: application/json

###

GET {{Service1_HostAddress}}/api-docs/index.html
Accept: application/json

###

GET {{Service1_HostAddress}}/scalar/v1
Accept: application/json

###